### ISSUE TITLE
Dependencies ?

### ISSUE THREAD

**Issue by ls-devs** [NeshHari/XMonad#2]
Hi,
First off what a beautifull setup !
I've tried to install it, with not much success.

So far, I've correctly installed Xmonad, following the documentation provided on the their website.
Without your files, everything works pretty fine.

I might be missing some deps for your setup to work correctly, can you maybe provide a list or something we need to make it works ?

**Comment by NeshHari** [comment]
Thank you for bringing this to my attention. I apologise for any inconvenience caused. Tbh I should have done this from the very beginning, though my focus was having a deployable NixOS configuration. Will update the docs very soon with a list of required and optional packages. Currently testing on a VM and trying to find alternatives for some AUR packages that are no longer maintained. Let's leave this issue open till I update the README.

**Comment by NeshHari** [comment]
Tested on 3 fresh installations of Arch and no issues. Updated the README too with installation notes. I'll close this now.
