### ISSUE TITLE
Trying out the configuration on a minimal arch VM

### ISSUE THREAD

**Issue by 4Gettt25** [NeshHari/XMonad#7]
Firstly I really love the look of both configurations. Secondly, I just bought a new Laptop for Uni and thought "Hey why not try arch with a window manager again" and that's when I found your XMonad configuration. So I wanted to try it out in a VM first but ran into some problems. I did a minimal arch install and then tried both the manual and the automatic installation of the config. But it never really worked as I couldn't even get into XMonad (which is 100% my fault) so I wanted to ask for some tips/tricks about the setup.

**Comment by NeshHari** [comment]
Hi. Is there an error message when running "startx" from the tty? Also run `xmonad --recompile` (in a tty session) to see any compilation-related message (can't find module etc.) and post it here. If the latter has no error and says "recompiled successfully", then it might be a graphic driver-related issue (esp if its nvidia). You may also want to try if you can launch into xmonad using the AUR package and simply copying over the configs + running `xmonad --recompile && xmonad --restart`, followed by `autorandr single`. The main difference (between the AUR package and mine -- stack install) is that the Haskell LSP won't work out-of-the-box (something to do with static/dynamic linking but I can't recall).

**Comment by 4Gettt25** [comment]
![xmonad error](https://user-images.githubusercontent.com/126004052/236614085-a8335c97-24dd-4b1f-9906-943261f3e3ae.png)

I had this error in the beginning after trying xmonad --recompile and noticed that the xmonad.hs wasn't in the right directory so I just copied it there and now it compiles with success but now I get the following error 

![openDisplay error](https://user-images.githubusercontent.com/126004052/236615460-53a8e08c-968f-4c70-8eb7-e7d1f0e8e659.png)

**Comment by 4Gettt25** [comment]
So I now got it to recompile with success but ran into another error: 
 
![openDisplay error](https://user-images.githubusercontent.com/126004052/236615822-cc474333-21c7-4c00-bad8-263274eca947.png)

**Comment by NeshHari** [comment]
This is expected behavior since xmonad can't be restarted within the tty. Since it recompiled successfully, there are no issues with the configuration. Please run "startx" to start the xmonad session. It reads the contents from ~/..xinitrc.

**Comment by 4Gettt25** [comment]
Okay when I do startx it starts but I just see a blackscreen

**Comment by NeshHari** [comment]
Does mod+Enter open kitty? If yes, run `autorandr --save single` then mod+q to restart and recompile xmonad.

**Comment by 4Gettt25** [comment]
No unfortunately mod+Enter doesn't open kitty

**Comment by 4Gettt25** [comment]
I FINALLY GOT IT TO WORK IN THE VM AFTER 8 HOURS!!!!!

**Comment by NeshHari** [comment]
> I FINALLY GOT IT TO WORK IN THE VM AFTER 8 HOURS!!!!!

Awesome :tada: ! If you have any suggestions/criticisms regarding the installation process, please feel free to list them :smiley: so I can make the necessary adjustments.

**Comment by 4Gettt25** [comment]
okay so I now set it up proberly but couldn't get 3 things to work. The First is polybar (it just shows the workspaces in the top middle, the second is eww-git (when I tried to install it I got the following error: "One or more PGP signatures could not be verified!") and the third is change my keyboard layout to german.

**Comment by 4Gettt25** [comment]
![eww error](https://user-images.githubusercontent.com/126004052/236676411-c2df5445-3648-4ea1-bb90-9ccebc2de3b7.png)
this is the complete eww error

**Comment by NeshHari** [comment]
I'm pretty sure polybar is only for the workspaces and the rest are eww. You may try updating the Arch Linux keyring with `sudo pacman -Syyu archlinux-keyring` first, and additionally import the gpg keys using `gpg --recv-keys <insert PK here>` if required. You may need to add/change the keyserver but try the aforementioned steps first. Please look [here](https://wiki.archlinux.org/title/Linux_console/Keyboard_configuration) for how to change keyboard layout.

**Comment by 4Gettt25** [comment]
I've noticed because I wanted to try the kanagawa one. That when you do wget https://raw.githubusercontent.com/NeshHari/XMonad/kanagawa/setup.sh it installs just the normal one

**Comment by 4Gettt25** [comment]
It also breaks when trying to change the resolution

**Comment by NeshHari** [comment]
Cool. I'll make the necessary adjustments when I find the time. Probably push the vertical branch as the new main since it completely abandons polybar and is eww-optimised (much better animations and functionality as well). Readme isn't updated though.

**Comment by 4Gettt25** [comment]
Okay then I will try vertical aswell

**Comment by 4Gettt25** [comment]
So I looked at some parts of the script and did 2 pull request (I tested it first an everything worked fine) so now both the kanagawa branch and vertical should point to the right branches

**Comment by 4Gettt25** [comment]
I've also noticed that the eww/polybar in kanagawa is really off center
